/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.EnemyToUI;
import controller.Controller;
import deepspace.GameState;

/**
 *
 * @author moises
 */
public class EnemyView extends javax.swing.JPanel {
    DamageView damageview;
    LootView lootview;
    
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        
        damageview=new DamageView();
        panelDamage.add(damageview);
        
        lootview=new LootView();
        panelLoot.add(lootview);
    }
    
    void setEnemy(EnemyToUI e){
        name.setText(e.getName());
        power.setText(Float.toString(e.getAmmoPower()));
        shieldpower.setText(Float.toString(e.getShieldPower()));
        
       
        damageview.setDamage(e.getDamage());
        //panelDamage.add(damageview);
        lootview.setLoot(e.getLoot());
        //panelLoot.add(lootview);
        
        GameState state=Controller.getInstance().getState();
       
        if(state==GameState.BEFORECOMBAT || state==GameState.INIT){
            lootview.setVisible(false);
            damageview.setVisible(false);
        }
        else{
            lootview.setVisible(true);
            damageview.setVisible(true);
        }
        

        repaint();
        revalidate();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tname = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Tpower = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        Tshield = new javax.swing.JLabel();
        shieldpower = new javax.swing.JLabel();
        panelLoot = new javax.swing.JPanel();
        panelDamage = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tname.setText("Name:");

        name.setText("jLabel2");

        Tpower.setText("Power:");

        power.setText("jLabel4");

        Tshield.setText("ShieldPower:");

        shieldpower.setText("jLabel6");

        panelLoot.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loot"));

        javax.swing.GroupLayout panelLootLayout = new javax.swing.GroupLayout(panelLoot);
        panelLoot.setLayout(panelLootLayout);
        panelLootLayout.setHorizontalGroup(
            panelLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panelLootLayout.setVerticalGroup(
            panelLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelDamage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Damage"));

        javax.swing.GroupLayout panelDamageLayout = new javax.swing.GroupLayout(panelDamage);
        panelDamage.setLayout(panelDamageLayout);
        panelDamageLayout.setHorizontalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        panelDamageLayout.setVerticalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tname)
                            .addComponent(Tpower)
                            .addComponent(Tshield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(power)
                            .addComponent(shieldpower)
                            .addComponent(name)))
                    .addComponent(panelLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tname)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tpower)
                    .addComponent(power))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tshield)
                    .addComponent(shieldpower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tname;
    private javax.swing.JLabel Tpower;
    private javax.swing.JLabel Tshield;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panelDamage;
    private javax.swing.JPanel panelLoot;
    private javax.swing.JLabel power;
    private javax.swing.JLabel shieldpower;
    // End of variables declaration//GEN-END:variables
}
