/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.LootToUI;
/**
 *
 * @author moises
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        supplies.setText(Integer.toString(loot.getnSupplies()));
        weapons.setText(Integer.toString(loot.getnWeapons()));
        shields.setText(Integer.toString(loot.getnShields()));
        hangar.setText(Integer.toString(loot.getnHangars()));
        medals.setText(Integer.toString(loot.getnMedals()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tsupplies = new javax.swing.JLabel();
        Tweapons = new javax.swing.JLabel();
        Tshields = new javax.swing.JLabel();
        Thangars = new javax.swing.JLabel();
        Tmedals = new javax.swing.JLabel();
        supplies = new javax.swing.JLabel();
        weapons = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        hangar = new javax.swing.JLabel();
        medals = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tsupplies.setText("Supplies:");

        Tweapons.setText("Weapons:");

        Tshields.setText("Shields:");

        Thangars.setText("Hangars:");

        Tmedals.setText("Medals:");

        supplies.setText("sssss");

        weapons.setText("wwwww");

        shields.setText("ssssss");

        hangar.setText("hhhhh");

        medals.setText("mmmmm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tweapons)
                            .addComponent(Tsupplies))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weapons)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tshields)
                        .addGap(27, 27, 27)
                        .addComponent(shields))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Thangars)
                            .addComponent(Tmedals))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medals)
                            .addComponent(hangar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tsupplies)
                    .addComponent(supplies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tweapons)
                    .addComponent(weapons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tshields)
                    .addComponent(shields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thangars)
                    .addComponent(hangar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tmedals)
                    .addComponent(medals)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Thangars;
    private javax.swing.JLabel Tmedals;
    private javax.swing.JLabel Tshields;
    private javax.swing.JLabel Tsupplies;
    private javax.swing.JLabel Tweapons;
    private javax.swing.JLabel hangar;
    private javax.swing.JLabel medals;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel supplies;
    private javax.swing.JLabel weapons;
    // End of variables declaration//GEN-END:variables
}
